# Generated by Django 4.1.7 on 2023-03-15 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
