# Generated by Django 4.1.7 on 2023-05-04 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_orderplaced_order_orderplaced_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
